// Writes .env.local (worker + shared) and apps/web/.env.local for the local stack.
// Values you edit yourself (API keys, provider choices) are preserved on every run.
// Usage: node scripts/local-env.mjs '<output of `supabase status -o json`>'
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const root = new URL("..", import.meta.url).pathname;
const status = JSON.parse(process.argv[2] ?? "{}");
if (!status.API_URL || !status.SERVICE_ROLE_KEY) {
  console.error("Supabase status is missing API_URL / SERVICE_ROLE_KEY. Is `supabase start` running?");
  process.exit(1);
}

const parse = (file) =>
  existsSync(file)
    ? Object.fromEntries(
        readFileSync(file, "utf8")
          .split("\n")
          .filter((l) => l.includes("=") && !l.trim().startsWith("#"))
          .map((l) => [l.slice(0, l.indexOf("=")).trim(), l.slice(l.indexOf("=") + 1).trim()]),
      )
    : {};

const existing = parse(`${root}.env.local`);
const keep = (key, fallback) => existing[key] ?? fallback;

// Managed by this script (recomputed each run).
const managed = {
  APP_ENV: "development",
  NEXT_PUBLIC_APP_URL: "http://localhost:3000",
  NEXT_PUBLIC_SUPABASE_URL: status.API_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: status.ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: status.SERVICE_ROLE_KEY,
  R2_ENDPOINT: "http://localhost:8333",
  R2_ACCESS_KEY_ID: "local-access-key",
  R2_SECRET_ACCESS_KEY: "local-secret-key-not-for-production",
  R2_BUCKET: "clips-local",
  S3_FORCE_PATH_STYLE: "true",
  WORKER_ENDPOINT_URL: "http://localhost:8787",
  ORCHESTRATOR: "local",
};

// Yours to edit in .env.local (kept across runs).
const user = {
  WORKER_SHARED_SECRET: keep("WORKER_SHARED_SECRET", randomBytes(32).toString("hex")),
  ANTHROPIC_API_KEY: keep("ANTHROPIC_API_KEY", ""),
  SEGMENTS_PROVIDER: keep("SEGMENTS_PROVIDER", "claude"),
  CLAUDE_MODEL_DEFAULT: keep("CLAUDE_MODEL_DEFAULT", "claude-sonnet-5-5"),
  CLAUDE_EFFORT: keep("CLAUDE_EFFORT", "medium"),
  TRANSCRIPTION_PROVIDER: keep("TRANSCRIPTION_PROVIDER", "whisper"),
  WHISPER_MODEL: keep("WHISPER_MODEL", "small"),
  ASSEMBLYAI_API_KEY: keep("ASSEMBLYAI_API_KEY", ""),
  CLIPS_TO_RENDER: keep("CLIPS_TO_RENDER", "3"),
  MAX_SOURCE_MINUTES: keep("MAX_SOURCE_MINUTES", "30"),
  LOCAL_WORKER_THREADS: keep("LOCAL_WORKER_THREADS", "2"),
  NEXT_PUBLIC_AUTH_GOOGLE_ENABLED: keep("NEXT_PUBLIC_AUTH_GOOGLE_ENABLED", "false"),
  BILLING_PROVIDER: keep("BILLING_PROVIDER", "fake"),
  STRIPE_SECRET_KEY: keep("STRIPE_SECRET_KEY", ""),
  STRIPE_WEBHOOK_SECRET: keep("STRIPE_WEBHOOK_SECRET", ""),
};

const lines = (obj) => Object.entries(obj).map(([k, v]) => `${k}=${v}`).join("\n");
writeFileSync(
  `${root}.env.local`,
  `# Local stack settings. Generated by scripts/local-up.sh. Never commit this file.\n` +
    `# --- Managed automatically ---\n${lines(managed)}\n\n` +
    `# --- Yours to edit (preserved) ---\n` +
    `# ANTHROPIC_API_KEY: required for real clip selection (pay-as-you-go, no subscription).\n` +
    `# TRANSCRIPTION_PROVIDER: whisper (local, free) | assemblyai (needs ASSEMBLYAI_API_KEY).\n` +
    `# SEGMENTS_PROVIDER: claude | fake (offline smoke test only, picks passages by length).\n` +
    `# BILLING_PROVIDER: fake (simulated payments) | stripe (test keys + "stripe listen", see docs/phase-5.md).\n` +
    `${lines(user)}\n`,
  { mode: 0o600 },
);

const webKeys = ["APP_ENV", "NEXT_PUBLIC_APP_URL", "NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY", "R2_ENDPOINT", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY", "R2_BUCKET",
  "S3_FORCE_PATH_STYLE", "WORKER_ENDPOINT_URL", "ORCHESTRATOR", "NEXT_PUBLIC_AUTH_GOOGLE_ENABLED", "BILLING_PROVIDER",
  "STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"];
const all = { ...managed, ...user };
writeFileSync(
  `${root}apps/web/.env.local`,
  `# Generated by scripts/local-up.sh from ../../.env.local. Do not edit here.\n` +
    lines({ ...Object.fromEntries(webKeys.map((k) => [k, all[k]])), WORKER_SHARED_SECRET: all.WORKER_SHARED_SECRET }) +
    "\n",
  { mode: 0o600 },
);

if (user.SEGMENTS_PROVIDER === "claude" && !user.ANTHROPIC_API_KEY) {
  console.warn(
    "\n[!] ANTHROPIC_API_KEY is empty in .env.local: clip selection will fail.\n" +
      "    Add your key there (console.anthropic.com), or set SEGMENTS_PROVIDER=fake for an offline test.\n",
  );
}
console.log("Wrote .env.local and apps/web/.env.local");
